apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongo-root-username: {{ .Values.secrets.mongoRootUsername | quote }}
  mongo-root-password: {{ .Values.secrets.mongoRootPassword | quote }}
