apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: email-config
  labels:
    release: prometheus
spec:
  route:
    receiver: email-receiver
  receivers:
    - name: email-receiver
      emailConfigs:
        - to: ops@example.com
          from: alerts@example.com
          smarthost: smtp.example.com:587
          authUsername: alerts@example.com
          authPassword:
            name: smtp-secret
            key: password
